### PR TITLE
format seconds converter

### PR DESCRIPTION
**Pull request by nikoloza**

### CODE REVIEW

**Comment by jimdebeer** [comment]
looks good but can you add a test for it?
cases include
- [ ] only seconds
- [ ] only minutes
- [ ] only hours

**Comment by nikoloza** [comment]
Yes, will do it

**Comment by jimdebeer** [comment]
Now as an extra requirement you need to write the docs for it as well
@shawninder will write down an example somewhere tommorow

**Comment by shawninder** [comment]
[vigour-util](https://github.com/vigour-io/util) is now a pretty good example on how to document and test stuff. @nikoloza Does this help?

**Pull request closed without merging**
